export default {
  LOAD_ADS_SUCCESS: "LOAD_ADS_SUCCESS",
  ADD_AD_SUCCESS: "ADD_AD_SUCCESS",
  UPDATE_AD_SUCCESS: "UPDATE_AD_SUCCESS",
  LOAD_STATES_SUCCESS: "LOAD_STATES_SUCCESS",
  LOAD_PET_TYPES_SUCCESS: "LOAD_PET_TYPES_SUCCESS",
  LOAD_AD_TYPES_SUCCESS: "LOAD_AD_TYPES_SUCCESS"

}