export default {
  LOAD_ADS_SUCCESS: "LOAD_ADS_SUCCESS",
  ADD_AD_SUCCESS: "ADD_AD_SUCCESS",
  UPDATE_AD_SUCCESS: "UPDATE_AD_SUCCESS",
  DELETE_AD_SUCCESS: "DELETE_AD_SUCCESS",
  LOAD_STATES_SUCCESS: "LOAD_STATES_SUCCESS",
  LOAD_PET_TYPES_SUCCESS: "LOAD_PET_TYPES_SUCCESS",
  LOAD_AD_TYPES_SUCCESS: "LOAD_AD_TYPES_SUCCESS",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",
  LOAD_USER_FROM_STORAGE: "LOAD_USER_FROM_STORAGE",
  LOAD_SUBSCRIPTIONS_SUCCESS: "LOAD_SUBSCRIPTION_SUCCESS",
  ADD_SUBSCRIPTION_SUCCESS: "ADD_SUBSCRIPTION_SUCCESS",
  UPDATE_SUBSCRIPTION_SUCCESS: "UPDATE_SUBSCRIPTION_SUCCESS",
  DELETE_SUBSCRIPTION_SUCCESS: "DELETE_SUBSCRIPTION_SUCCESS",
  INCREMENT_APIS_IN_PROGRESS: "INCREMENT_APIS_IN_PROGRESS",
  DECREMENT_APIS_IN_PROGRESS: "DECREMENT_APIS_IN_PROGRESS"
}