export default {
  LOAD_ADS_SUCCESS: "LOAD_ADS_SUCCESS",
  ADD_AD_SUCCESS: "ADD_AD_SUCCESS",
  UPDATE_AD_SUCCESS: "UPDATE_AD_SUCCESS",
  LOAD_STATES_SUCCESS: "LOAD_STATES_SUCCESS",
  LOAD_PET_TYPES_SUCCESS: "LOAD_PET_TYPES_SUCCESS",
  LOAD_AD_TYPES_SUCCESS: "LOAD_AD_TYPES_SUCCESS",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",
  LOAD_USER_FROM_STORAGE: "LOAD_USER_FROM_STORAGE"
}